//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionTestCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CollectingErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CollectingErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegressionTestCollector.Resources.CollectingErrors", typeof(CollectingErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to create the text for clipboard.
        /// </summary>
        internal static string ClipboardCopyError {
            get {
                return ResourceManager.GetString("ClipboardCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was created for debug session. Have fun debugging!.
        /// </summary>
        internal static string CreatedDebugScriptCopy {
            get {
                return ResourceManager.GetString("CreatedDebugScriptCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to clean up debug session.
        /// </summary>
        internal static string DebugCleanUpError {
            get {
                return ResourceManager.GetString("DebugCleanUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug session was successfully cleaned up.
        /// </summary>
        internal static string DebugCleanUpSuccess {
            get {
                return ResourceManager.GetString("DebugCleanUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to create debug session.
        /// </summary>
        internal static string DebugCreationError {
            get {
                return ResourceManager.GetString("DebugCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was deleted.
        /// </summary>
        internal static string DeletingDebugFile {
            get {
                return ResourceManager.GetString("DeletingDebugFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to create and transform python script copy.
        /// </summary>
        internal static string ErrorCreatingAndTransformingPythonCopy {
            get {
                return ResourceManager.GetString("ErrorCreatingAndTransformingPythonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown while trying to create command string for clipboard.
        /// </summary>
        internal static string ErrorCreatingCopyCommandString {
            get {
                return ResourceManager.GetString("ErrorCreatingCopyCommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happend while parsing bat file. Following arguments are missing.
        /// </summary>
        internal static string ErrorParsingBatFile {
            get {
                return ResourceManager.GetString("ErrorParsingBatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happend while parsing config file.
        /// </summary>
        internal static string ErrorParsingConfigFile {
            get {
                return ResourceManager.GetString("ErrorParsingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while parsing definition file.
        /// </summary>
        internal static string ErrorParsingDefinitionFile {
            get {
                return ResourceManager.GetString("ErrorParsingDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to run python script copy.
        /// </summary>
        internal static string ErrorRunningPythonCopy {
            get {
                return ResourceManager.GetString("ErrorRunningPythonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled loading process.
        /// </summary>
        internal static string LoadingCanceledInfo {
            get {
                return ResourceManager.GetString("LoadingCanceledInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors were encountered. When selecting a folder that includes not supported RegTests encountering errors is expected..
        /// </summary>
        internal static string LoadingErrorsEncountered {
            get {
                return ResourceManager.GetString("LoadingErrorsEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tests were found.
        /// </summary>
        internal static string LoadingTestsFound {
            get {
                return ResourceManager.GetString("LoadingTestsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to find python script.
        /// </summary>
        internal static string NoPythonScript {
            get {
                return ResourceManager.GetString("NoPythonScript", resourceCulture);
            }
        }
    }
}
