//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionTestCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchTableString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchTableString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegressionTestCollector.Resources.SearchTableString", typeof(SearchTableString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command String.
        /// </summary>
        public static string CommandStringHeader {
            get {
                return ResourceManager.GetString("CommandStringHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path.
        /// </summary>
        public static string ContextMenuAbsolutePath {
            get {
                return ResourceManager.GetString("ContextMenuAbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up debug session.
        /// </summary>
        public static string ContextMenuCleanUpDebugSession {
            get {
                return ResourceManager.GetString("ContextMenuCleanUpDebugSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy command.
        /// </summary>
        public static string ContextMenuCopyCommandString {
            get {
                return ResourceManager.GetString("ContextMenuCopyCommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy options.
        /// </summary>
        public static string ContextMenuCopyOptions {
            get {
                return ResourceManager.GetString("ContextMenuCopyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include exe.
        /// </summary>
        public static string ContextMenuExeInclusion {
            get {
                return ResourceManager.GetString("ContextMenuExeInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory in Explorer.
        /// </summary>
        public static string ContextMenuOpenFolder {
            get {
                return ResourceManager.GetString("ContextMenuOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare test for debug session.
        /// </summary>
        public static string ContextMenuPrepareForDebug {
            get {
                return ResourceManager.GetString("ContextMenuPrepareForDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative path.
        /// </summary>
        public static string ContextMenuRelativePath {
            get {
                return ResourceManager.GetString("ContextMenuRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add --debug.
        /// </summary>
        public static string ContextMenuSetDebug {
            get {
                return ResourceManager.GetString("ContextMenuSetDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add --verbose.
        /// </summary>
        public static string ContextMenuSetVerbose {
            get {
                return ResourceManager.GetString("ContextMenuSetVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐛 Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected test uses the same python script as another test. Do you want to stop the current debug session and start a new one with the selected test?.
        /// </summary>
        public static string DebugWarningText {
            get {
                return ResourceManager.GetString("DebugWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugWarningTitle {
            get {
                return ResourceManager.GetString("DebugWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string FilterControlClearAll {
            get {
                return ResourceManager.GetString("FilterControlClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupNameHeader {
            get {
                return ResourceManager.GetString("GroupNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux.
        /// </summary>
        public static string PlatformLinux {
            get {
                return ResourceManager.GetString("PlatformLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string PlatformWindows {
            get {
                return ResourceManager.GetString("PlatformWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TestNameHeader {
            get {
                return ResourceManager.GetString("TestNameHeader", resourceCulture);
            }
        }
    }
}
