//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionTestCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegressionTestCollector.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string CancelLoadingProcessButton {
            get {
                return ResourceManager.GetString("CancelLoadingProcessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently in a debug session. Are you sure you want to close the session and the program?.
        /// </summary>
        public static string DebugWarningText {
            get {
                return ResourceManager.GetString("DebugWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DebugWarningTitle {
            get {
                return ResourceManager.GetString("DebugWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Filter.
        /// </summary>
        public static string GroupNameFilterControl {
            get {
                return ResourceManager.GetString("GroupNameFilterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Collecting Strategy is native to the Regression Test Collector and is the recommended option.|Python Collecting Strategy uses an external python script, which is deprecated at the moment..
        /// </summary>
        public static string HelpCollectingStrategyBulletPoints {
            get {
                return ResourceManager.GetString("HelpCollectingStrategyBulletPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Collecting Strategy.
        /// </summary>
        public static string HelpCollectingStrategyHeader {
            get {
                return ResourceManager.GetString("HelpCollectingStrategyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose between different Collecting Strategies in the Menu..
        /// </summary>
        public static string HelpCollectingStrategyIntroText {
            get {
                return ResourceManager.GetString("HelpCollectingStrategyIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including the executable allows the command to be copied into a console.|Excluding the executable allows the command to be used as debug paramter in an IDE.|Selecting linux converts the paths to linux paths, so that the command can be run in WSL. If the compilers used change this feature may break and needs to be adjusted.|To run the command in verbose or debug mode us --debug and --verbose.
        /// </summary>
        public static string HelpCommandStringBulletPoints {
            get {
                return ResourceManager.GetString("HelpCommandStringBulletPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command string can be copied through the table context menu. You can choose between different copy settings based on your needs..
        /// </summary>
        public static string HelpCopyingCommandStringIntroText {
            get {
                return ResourceManager.GetString("HelpCopyingCommandStringIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &apos;Load...&apos; button and select a folder in which regression tests are. It will scan the folder including subdirectories..
        /// </summary>
        public static string HelpHowToLoadData {
            get {
                return ResourceManager.GetString("HelpHowToLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data.
        /// </summary>
        public static string HelpHowToLoadDataHeader {
            get {
                return ResourceManager.GetString("HelpHowToLoadDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing a debug session for HTTP-Tests.
        /// </summary>
        public static string HelpHowToPrepareDebugSessionHeader {
            get {
                return ResourceManager.GetString("HelpHowToPrepareDebugSessionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying the Command String.
        /// </summary>
        public static string HelpHowToUseCommandString {
            get {
                return ResourceManager.GetString("HelpHowToUseCommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select prepare test for debug session in the context menu of a test.|Start a Http-Server in debug mode with your IDE.|After the server is started run the python script with _RTC suffix in debug mode.|Close the debug session after you are done debugging. This will clean up the debug file..
        /// </summary>
        public static string HelpHttpServerSteps {
            get {
                return ResourceManager.GetString("HelpHttpServerSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use the Regression Test Collector - CANdelaStudio Server Edition.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned off.
        /// </summary>
        public static string HighlighterIsTurnedOffOptionLabel {
            get {
                return ResourceManager.GetString("HighlighterIsTurnedOffOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter.
        /// </summary>
        public static string HighlighterMenu {
            get {
                return ResourceManager.GetString("HighlighterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping loading process....
        /// </summary>
        public static string LoadingProcessStopped {
            get {
                return ResourceManager.GetString("LoadingProcessStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        public static string MenuChangeThemeToggle {
            get {
                return ResourceManager.GetString("MenuChangeThemeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string MenuCollectingMethodCSharpName {
            get {
                return ResourceManager.GetString("MenuCollectingMethodCSharpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use internal collecting strategy implemented in C#. Select the folder in which you want to search for Regression Tests..
        /// </summary>
        public static string MenuCollectingMethodCSharpTooltip {
            get {
                return ResourceManager.GetString("MenuCollectingMethodCSharpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python.
        /// </summary>
        public static string MenuCollectingMethodPythonName {
            get {
                return ResourceManager.GetString("MenuCollectingMethodPythonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use external collecting strategy implemented in Python. Select the ListRegressionTests.py script..
        /// </summary>
        public static string MenuCollectingMethodPythonTooltip {
            get {
                return ResourceManager.GetString("MenuCollectingMethodPythonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet :(.
        /// </summary>
        public static string MenuHelpNotImplemented {
            get {
                return ResourceManager.GetString("MenuHelpNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        public static string MenuLoad {
            get {
                return ResourceManager.GetString("MenuLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to python.
        /// </summary>
        public static string MenuPythonCommandPython {
            get {
                return ResourceManager.GetString("MenuPythonCommandPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to python3.
        /// </summary>
        public static string MenuPythonCommandPython3 {
            get {
                return ResourceManager.GetString("MenuPythonCommandPython3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Methods.
        /// </summary>
        public static string MenuSelectCollectingMethod {
            get {
                return ResourceManager.GetString("MenuSelectCollectingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Command.
        /// </summary>
        public static string MenuSelectPythonCommand {
            get {
                return ResourceManager.GetString("MenuSelectPythonCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which python command should be used for running python scripts.
        /// </summary>
        public static string MenuSelectPythonCommandTooltip {
            get {
                return ResourceManager.GetString("MenuSelectPythonCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Output.
        /// </summary>
        public static string MenuShowOutput {
            get {
                return ResourceManager.GetString("MenuShowOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create text report....
        /// </summary>
        public static string MenuTextReport {
            get {
                return ResourceManager.GetString("MenuTextReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string MenuThemeDark {
            get {
                return ResourceManager.GetString("MenuThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string MenuThemeLight {
            get {
                return ResourceManager.GetString("MenuThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string MenuThemes {
            get {
                return ResourceManager.GetString("MenuThemes", resourceCulture);
            }
        }
    }
}
